/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author 9fdam05
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        BaseDatos = new javax.swing.JMenu();
        Proveedores = new javax.swing.JMenu();
        GestionProveedores = new javax.swing.JMenu();
        ConsultaProveedores = new javax.swing.JMenu();
        codigoProv = new javax.swing.JMenu();
        nombreProv = new javax.swing.JMenu();
        direccionProv = new javax.swing.JMenu();
        Piezas = new javax.swing.JMenu();
        gestionPiezas = new javax.swing.JMenu();
        consultaPiezas = new javax.swing.JMenu();
        codigoPie = new javax.swing.JMenu();
        nombrePie = new javax.swing.JMenu();
        Proyectos = new javax.swing.JMenu();
        gestionProyectos = new javax.swing.JMenu();
        consultaProyesctos = new javax.swing.JMenu();
        codigoProy = new javax.swing.JMenu();
        nombreProy = new javax.swing.JMenu();
        ciudadProy = new javax.swing.JMenu();
        Gestion = new javax.swing.JMenu();
        Piezas_proveedores_proyectos = new javax.swing.JMenu();
        Suministros_por_proveedor = new javax.swing.JMenu();
        Suministros_por_piezas = new javax.swing.JMenu();
        Estadísticas = new javax.swing.JMenu();
        Ayuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        BaseDatos.setText("Base de datos");
        jMenuBar1.add(BaseDatos);

        Proveedores.setText("Proveedores");

        GestionProveedores.setText("Gestión de Proveedores");
        GestionProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GestionProveedoresMouseClicked(evt);
            }
        });
        Proveedores.add(GestionProveedores);

        ConsultaProveedores.setText("Consulta de Proveedores");

        codigoProv.setText("Por codigo");
        codigoProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigoProvMouseClicked(evt);
            }
        });
        ConsultaProveedores.add(codigoProv);

        nombreProv.setText("Por nombre");
        nombreProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreProvMouseClicked(evt);
            }
        });
        ConsultaProveedores.add(nombreProv);

        direccionProv.setText("Por direccion");
        direccionProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                direccionProvMouseClicked(evt);
            }
        });
        ConsultaProveedores.add(direccionProv);

        Proveedores.add(ConsultaProveedores);

        jMenuBar1.add(Proveedores);

        Piezas.setText("Piezas");

        gestionPiezas.setText("Gestión de piezas");
        gestionPiezas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionPiezasMouseClicked(evt);
            }
        });
        Piezas.add(gestionPiezas);

        consultaPiezas.setText("Consulta de piezas");

        codigoPie.setText("Por codigo");
        codigoPie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigoPieMouseClicked(evt);
            }
        });
        consultaPiezas.add(codigoPie);

        nombrePie.setText("Por nombre");
        nombrePie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombrePieMouseClicked(evt);
            }
        });
        consultaPiezas.add(nombrePie);

        Piezas.add(consultaPiezas);

        jMenuBar1.add(Piezas);

        Proyectos.setText("Proyectos");

        gestionProyectos.setText("Gestión de proyectos");
        gestionProyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gestionProyectosMouseClicked(evt);
            }
        });
        Proyectos.add(gestionProyectos);

        consultaProyesctos.setText("Consulta de proyectos");

        codigoProy.setText("Por codigo");
        codigoProy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigoProyMouseClicked(evt);
            }
        });
        consultaProyesctos.add(codigoProy);

        nombreProy.setText("Por nombre");
        nombreProy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreProyMouseClicked(evt);
            }
        });
        consultaProyesctos.add(nombreProy);

        ciudadProy.setText("Por ciudad");
        ciudadProy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ciudadProyMouseClicked(evt);
            }
        });
        consultaProyesctos.add(ciudadProy);

        Proyectos.add(consultaProyesctos);

        jMenuBar1.add(Proyectos);

        Gestion.setText("Gestion global");

        Piezas_proveedores_proyectos.setText("Piezas, proveedores y proyectos");
        Piezas_proveedores_proyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Piezas_proveedores_proyectosMouseClicked(evt);
            }
        });
        Gestion.add(Piezas_proveedores_proyectos);

        Suministros_por_proveedor.setText("Suministros por proveedor");
        Suministros_por_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Suministros_por_proveedorMouseClicked(evt);
            }
        });
        Gestion.add(Suministros_por_proveedor);

        Suministros_por_piezas.setText("Suministros por piezas");
        Suministros_por_piezas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Suministros_por_piezasMouseClicked(evt);
            }
        });
        Gestion.add(Suministros_por_piezas);

        Estadísticas.setText("Estadísticas");
        Estadísticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstadísticasMouseClicked(evt);
            }
        });
        Gestion.add(Estadísticas);

        jMenuBar1.add(Gestion);

        Ayuda.setText("Ayuda");
        Ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AyudaMouseClicked(evt);
            }
        });
        jMenuBar1.add(Ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestionProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionProveedoresMouseClicked
        GestionProveedores gestionProveedores = new GestionProveedores();
        gestionProveedores.setLocationRelativeTo(null);
        gestionProveedores.setVisible(true);
    }//GEN-LAST:event_GestionProveedoresMouseClicked

    private void codigoProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoProvMouseClicked
        ConsultaProveedoresCodigo consultaProveedoresCodigo = new ConsultaProveedoresCodigo();
        consultaProveedoresCodigo.setLocationRelativeTo(null);
        consultaProveedoresCodigo.setVisible(true);
    }//GEN-LAST:event_codigoProvMouseClicked

    private void nombreProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreProvMouseClicked
        ConsultaProveedoresNombre consultaProveedoresNombre = new ConsultaProveedoresNombre();
        consultaProveedoresNombre.setLocationRelativeTo(null);
        consultaProveedoresNombre.setVisible(true);
    }//GEN-LAST:event_nombreProvMouseClicked

    private void direccionProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direccionProvMouseClicked
        ConsultaProveedoresDireccion consultaProveedoresDireccion = new ConsultaProveedoresDireccion();
        consultaProveedoresDireccion.setLocationRelativeTo(null);
        consultaProveedoresDireccion.setVisible(true);
    }//GEN-LAST:event_direccionProvMouseClicked

    private void gestionPiezasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionPiezasMouseClicked
        GestionPiezas gestionPiezas = new GestionPiezas();
        gestionPiezas.setLocationRelativeTo(null);
        gestionPiezas.setVisible(true);
    }//GEN-LAST:event_gestionPiezasMouseClicked

    private void codigoPieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoPieMouseClicked
        ConsultaPiezasCodigo consultapiezascodigo = new ConsultaPiezasCodigo();
        consultapiezascodigo.setLocationRelativeTo(null);
        consultapiezascodigo.setVisible(true);
    }//GEN-LAST:event_codigoPieMouseClicked

    private void nombrePieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombrePieMouseClicked
        ConsultaPiezasNombre consultaPiezasNombre = new ConsultaPiezasNombre();
        consultaPiezasNombre.setLocationRelativeTo(null);
        consultaPiezasNombre.setVisible(true);
    }//GEN-LAST:event_nombrePieMouseClicked

    private void gestionProyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gestionProyectosMouseClicked
        GestionProyectos gestionproyectos = new GestionProyectos();
        gestionproyectos.setLocationRelativeTo(null);
        gestionproyectos.setVisible(true);
    }//GEN-LAST:event_gestionProyectosMouseClicked

    private void codigoProyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoProyMouseClicked
        ConsultaProyectosCodigo consultaProyectosCodigo = new ConsultaProyectosCodigo();
        consultaProyectosCodigo.setLocationRelativeTo(null);
        consultaProyectosCodigo.setVisible(true);
    }//GEN-LAST:event_codigoProyMouseClicked

    private void nombreProyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreProyMouseClicked
        ConsultaProyectosNombre consultaProyectosNombre = new ConsultaProyectosNombre();
        consultaProyectosNombre.setLocationRelativeTo(null);
        consultaProyectosNombre.setVisible(true);
    }//GEN-LAST:event_nombreProyMouseClicked

    private void ciudadProyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ciudadProyMouseClicked
        ConsultaProyectosCiudad consultaProyectosCiudad = new ConsultaProyectosCiudad();
        consultaProyectosCiudad.setLocationRelativeTo(null);
        consultaProyectosCiudad.setVisible(true);
    }//GEN-LAST:event_ciudadProyMouseClicked

    private void Piezas_proveedores_proyectosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Piezas_proveedores_proyectosMouseClicked
        GestionPPP gestionPPP = new GestionPPP();
        gestionPPP.setLocationRelativeTo(null);
        gestionPPP.setVisible(true);
    }//GEN-LAST:event_Piezas_proveedores_proyectosMouseClicked

    private void Suministros_por_proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Suministros_por_proveedorMouseClicked
        SuministrosProveedor suministrosProveedor = new SuministrosProveedor();
        suministrosProveedor.setLocationRelativeTo(null);
        suministrosProveedor.setVisible(true);
    }//GEN-LAST:event_Suministros_por_proveedorMouseClicked

    private void Suministros_por_piezasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Suministros_por_piezasMouseClicked
        SuministrosPiezas suministrosPiezas = new SuministrosPiezas();
        suministrosPiezas.setLocationRelativeTo(null);
        suministrosPiezas.setVisible(true);
    }//GEN-LAST:event_Suministros_por_piezasMouseClicked

    private void EstadísticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadísticasMouseClicked
        SuministrosPiezas suministrosPiezas = new SuministrosPiezas();
        suministrosPiezas.setLocationRelativeTo(null);
        suministrosPiezas.setVisible(true);
    }//GEN-LAST:event_EstadísticasMouseClicked

    private void AyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AyudaMouseClicked
        Ayuda ayuda = new Ayuda();
        ayuda.setLocationRelativeTo(null);
        ayuda.setVisible(true);
    }//GEN-LAST:event_AyudaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ayuda;
    private javax.swing.JMenu BaseDatos;
    private javax.swing.JMenu ConsultaProveedores;
    private javax.swing.JMenu Estadísticas;
    private javax.swing.JMenu Gestion;
    private javax.swing.JMenu GestionProveedores;
    private javax.swing.JMenu Piezas;
    private javax.swing.JMenu Piezas_proveedores_proyectos;
    private javax.swing.JMenu Proveedores;
    private javax.swing.JMenu Proyectos;
    private javax.swing.JMenu Suministros_por_piezas;
    private javax.swing.JMenu Suministros_por_proveedor;
    private javax.swing.JMenu ciudadProy;
    private javax.swing.JMenu codigoPie;
    private javax.swing.JMenu codigoProv;
    private javax.swing.JMenu codigoProy;
    private javax.swing.JMenu consultaPiezas;
    private javax.swing.JMenu consultaProyesctos;
    private javax.swing.JMenu direccionProv;
    private javax.swing.JMenu gestionPiezas;
    private javax.swing.JMenu gestionProyectos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu nombrePie;
    private javax.swing.JMenu nombreProv;
    private javax.swing.JMenu nombreProy;
    // End of variables declaration//GEN-END:variables
}
